### PR TITLE
Bounding circle support

### PR DESCRIPTION
**Pull request by ppiotrow**
Method to return all zones that are inside bounding circle

### CODE REVIEW

**Comment by ppiotrow** [comment]
I'm not able to check why build has failed. Locally the tests are working. Please share details with me.

**Comment by shishkin** [comment]
@ppiotrow Thanks for your contribution! Unfortunately I don't know why the build fails as Travis link for this build is somehow broken.

Regarding the feature itself, we're not planning to further develop the geohex algorithm as I wasn't able to reverse engineer it from code. That's why we built the terahex algorithm and plan to remove geohex from the library. So if you're interested in geohex, I suggest you to maintain your own fork of it. Please let me know of your use case and if you're interested in contributing to terahex.

**Comment by ppiotrow** [comment]
I might be interested in contributing to terahex, however I'm not able to understand idea behind it just by reading javadocs. Do you plan to release some documentation?

**Comment by shishkin** [comment]
Yes, although the API and the implementation are still in flux. The main difference is that the grid size is configurable. This allows to choose the initial grid size so that a hexagon at a certain level has a desired metric size. If you have a concrete question, feel free ask. That way I would know which parts need more clarification.

**Pull request closed without merging**
